openapi: '3.0.2'
info:
  title: Recipe API
  version: '1.0.0'
servers:
  - url: https://api.server.test/v1
paths:
  /recipes:
    get:
      operationId: Recipes
      description: レシピ
      tags:
        - recipe
      parameters:
        - in: query
          name: q
          schema:
            type: string
          example: トマト
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeCollection'
        '404':
          $ref: '#/components/responses/NotFound'
        '425':
          $ref: '#/components/responses/RequestValidationError'
        '500':
          $ref: '#/components/responses/Unknown'
components:
  responses:
    NotFound:
      description: 'Not Found'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceNotFound'
    Unknown:
      description: 'Unknown error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    RequestValidationError:
      description: 'Validation error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'

  schemas:
    Error:
      type: object
      required:
        - type
        - title
      properties:
        type:
          type: string
          example: ''
        title:
          type: string
          example: ''
        detail:
          type: string
          example: ''
    ValidationError:
      type: object
      required:
        - type
        - title
      properties:
        type:
          type: string
          example: ''
        title:
          type: string
          example: ''
        invalid_params:
          type: array
          items:
            $ref: '#/components/schemas/InvalidParam'
    InvalidParam:
      type: object
      properties:
        name:
          type: string
          example: ''
        reason:
          type: string
          example: ''
    ResourceNotFound:
      type: object
      required:
        - type
        - title
      properties:
        type:
          type: string
          example: ''
        title:
          type: string
          example: ''
        detail:
          type: string
          example: ''

    RecipeCollection:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          description: レシピの配列
          items:
            $ref: '#/components/schemas/Recipe'
    Recipe:
      description: レシピ
      type: object
      required:
        - postalcode
      properties:
        url:
          type: string
          description: URL
          example: https://example.com/
        title:
          type: string
          description: レシピ名
          example: 簡単！筍と豚肉のチンジャオロース風
        ingredient:
          type: string
          description: 材料
          example: |
            きゅうり 2本
            醤油 大さじ2
            海苔　1枚
        instruction:
          type: string
          description: 作り方
          example: |
            ①きゅうりをちぎってボウルへ
            ②醤油の加えて海苔を和えれば完成
        created_at:
          type: string
          format: date-time
          description: 作成日時
          example: "2021-07-14T07:56:42+09:00"
