version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "..:/app"
    command: make run
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ../gen/resources/openapi:/usr/share/nginx/html/openapi
    environment:
      API_URL: openapi/v1.yaml
  localstack:
    image: localstack/localstack
    environment:
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=sqs
